publishDir = "dist"
theme = "centerfold"
baseURL = "https://www.theoberlingrape.com/"
languageCode = "en-us"
title = "The Oberlin Grape"
MetaDataFormat = "toml"
googleAnalytics = ""

[params]
  backgroundColor = "f7f7f7"
  showBorder = false
  font = "Montserrat"
  copyright = "&copy; All rights reserved. Powered by [Hugo](https://gohugo.io). The Oberlin Grape. 2017"
  favicon = "pixel-logo.png"
  submissionBoxMessage = "Become a contributor! Enter your email below and we'll reach out to talk about your story idea. Don't have one? You can take one of ours."

[[menu.main]]
  url = "/post/bad-habits/"
  name = "Bad Habits"
  pre = "ffe9ff"
  weight = 1
  
[[menu.main]]
  url = "/post/features/"
  name = "Features"
  pre = "f2f623"
  weight = 2

[[menu.main]]
  url = "/post/opinions/"
  name = "Opinions"  
  pre = "6024a5"
  weight = 3  

[[menu.main]]
  url = "/post/arts-culture/"
  name = "Arts&Culture"
 pre = "d30016"
  weight = 4
